### ISSUE TITLE
Issues Web interface

### ISSUE THREAD

**Issue by villamany** [grblHAL/ESP32#116]
Hello, I am trying GRBLhal for the first time but I am not able to get it to work through the web interface.
Using USB it works perfectly, but through the web interface I get error messages 1 and error messages 2 every time I send a Gcode command (only one in every 15 or 20 commands is executed without error). The Settings page is working fine over WebUi.
I have tried WebUi v2 and v3 with the same result. I'm using a DLC32 v2.1 board.

![Portapapeles-1](https://github.com/grblHAL/core/assets/5514002/5d8043f0-243e-4dfc-b849-38f6ec596d88)

**Comment by terjeio** [comment]
This was an odd one, could be a compiler bug, framwork bug or a memory leak? With the committed workarund everything seems ok, but I do not know why it failed with the original code which only added a check for a return value compared to earlier versions...

**Comment by terjeio** [comment]
Web Builder was updated after I committed th fix.

**Comment by villamany** [comment]
Thanks, seems to be working ok now.

One minor issue is if i don't have the Homing feature enabled and press the "Homing" button i get a correct error message "Homing failed. Homing is not enabled in settings", but if i now press the "Zero all axis" still the same error until i jog any axis and press "Zero all axis" again

Note: The web builder still showing "build 20240626"

**Comment by terjeio** [comment]
>  still the same error until i jog any axis and press "Zero all axis" again

Not sure I want to change this, as part of improving safety any non $ commands received after an error will be ignored and the same error reported. To clear the error a new $-command or a blank line has to be sent.

> Note: The web builder still showing "build 20240626"

This is the core version number, drivers has their own and the core version will not be changed on a driver change. The fix was for the ESP32 driver only.

**Comment by villamany** [comment]
Nice. Many thanks!
